Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 8080, host: 6060
  config.vm.network "forwarded_port", guest: 80, host: 5050
  config.vm.network "forwarded_port", guest: 3306, host: 33306
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
  SHELL
end
